/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import { motion } from "framer-motion";
import { FaCalendar, FaEnvelope, FaChartLine } from "react-icons/fa";

const Dashboard = () => {
  const [activeTab, setActiveTab] = useState("bookings");

  const tabContent = {
    bookings: [
      { id: 1, date: "2023-06-15", client: "John Doe", service: "Dog Walking" },
      {
        id: 2,
        date: "2023-06-16",
        client: "Jane Smith",
        service: "Cat Sitting",
      },
      {
        id: 3,
        date: "2023-06-17",
        client: "Mike Johnson",
        service: "Pet Grooming",
      },
    ],
    messages: [
      {
        id: 1,
        from: "Alice Brown",
        subject: "Website Inquiry",
        date: "2023-06-14",
      },
      {
        id: 2,
        from: "Bob White",
        subject: "Booking Question",
        date: "2023-06-15",
      },
      { id: 3, from: "Carol Green", subject: "Feedback", date: "2023-06-16" },
    ],
  };

  return (
    <div className="bg-gray-100 min-h-screen p-8">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="max-w-6xl mx-auto bg-white rounded-lg shadow-lg overflow-hidden"
      >
        <div className="flex bg-blue-500 text-white">
          <button
            className={`flex-1 py-4 px-6 focus:outline-none ${
              activeTab === "bookings" ? "bg-blue-600" : ""
            }`}
            onClick={() => setActiveTab("bookings")}
          >
            <FaCalendar className="inline-block mr-2" /> Bookings
          </button>
          <button
            className={`flex-1 py-4 px-6 focus:outline-none ${
              activeTab === "messages" ? "bg-blue-600" : ""
            }`}
            onClick={() => setActiveTab("messages")}
          >
            <FaEnvelope className="inline-block mr-2" /> Messages
          </button>
          <button
            className={`flex-1 py-4 px-6 focus:outline-none ${
              activeTab === "analytics" ? "bg-blue-600" : ""
            }`}
            onClick={() => setActiveTab("analytics")}
          >
            <FaChartLine className="inline-block mr-2" /> Analytics
          </button>
        </div>

        <div className="p-6">
          {activeTab === "bookings" && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.5 }}
            >
              <h2 className="text-2xl font-bold mb-4">Upcoming Bookings</h2>
              <table className="w-full">
                <thead>
                  <tr className="bg-gray-200">
                    <th className="p-2 text-left">Date</th>
                    <th className="p-2 text-left">Client</th>
                    <th className="p-2 text-left">Service</th>
                  </tr>
                </thead>
                <tbody>
                  {tabContent.bookings.map((booking) => (
                    <tr key={booking.id} className="border-b">
                      <td className="p-2">{booking.date}</td>
                      <td className="p-2">{booking.client}</td>
                      <td className="p-2">{booking.service}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </motion.div>
          )}

          {activeTab === "messages" && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.5 }}
            >
              <h2 className="text-2xl font-bold mb-4">Recent Messages</h2>
              <ul>
                {tabContent.messages.map((message) => (
                  <li key={message.id} className="border-b py-2">
                    <p className="font-semibold">{message.from}</p>
                    <p className="text-sm text-gray-600">{message.subject}</p>
                    <p className="text-xs text-gray-500">{message.date}</p>
                  </li>
                ))}
              </ul>
            </motion.div>
          )}

          {activeTab === "analytics" && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.5 }}
            >
              <h2 className="text-2xl font-bold mb-4">Website Analytics</h2>
              <div className="bg-gray-200 p-4 rounded-lg">
                <p className="text-center text-gray-600">
                  Analytics graph placeholder
                </p>
              </div>
            </motion.div>
          )}
        </div>
      </motion.div>
    </div>
  );
};

export default Dashboard;
