/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { render, screen, fireEvent } from "@testing-library/react";
import { describe, it, expect } from "vitest";
import Dashboard from "../Dashboard";

describe("Dashboard", () => {
  it("renders the dashboard with default bookings tab", () => {
    render(<Dashboard />);

    expect(screen.getByText("Upcoming Bookings")).toBeInTheDocument();
    expect(screen.getByText("John Doe")).toBeInTheDocument();
    expect(screen.getByText("Jane Smith")).toBeInTheDocument();
  });

  it("switches to messages tab when clicked", () => {
    render(<Dashboard />);

    fireEvent.click(screen.getByText("Messages"));

    expect(screen.getByText("Recent Messages")).toBeInTheDocument();
    expect(screen.getByText("Alice Brown")).toBeInTheDocument();
    expect(screen.getByText("Bob White")).toBeInTheDocument();
  });

  it("switches to analytics tab when clicked", () => {
    render(<Dashboard />);

    fireEvent.click(screen.getByText("Analytics"));

    expect(screen.getByText("Website Analytics")).toBeInTheDocument();
    expect(screen.getByText("Analytics graph placeholder")).toBeInTheDocument();
  });
});
