/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import { describe, it, expect } from "vitest";
import HeroSection from "../HeroSection";

describe("HeroSection", () => {
  it("renders the hero section with correct content", () => {
    render(<HeroSection />);

    expect(
      screen.getByText("I Design Tail-Wagging Websites for Pet Sitters")
    ).toBeInTheDocument();
    expect(
      screen.getByText(
        "Helping pet care businesses create playful, engaging, and effective websites."
      )
    ).toBeInTheDocument();
    expect(screen.getByText("Get a Free Consultation")).toBeInTheDocument();
    expect(screen.getByText("Let's Revamp Your Site")).toBeInTheDocument();
  });

  it("has accessible buttons", () => {
    render(<HeroSection />);

    const buttons = screen.getAllByRole("button");
    expect(buttons).toHaveLength(2);
    buttons.forEach((button) => {
      expect(button).toHaveAttribute("class");
      expect(button.className).toContain("text-white");
    });
  });
});
