/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import HeroSection from "../components/HeroSection";

describe("HeroSection", () => {
  it("renders the hero section with correct content", () => {
    render(<HeroSection />);

    expect(
      screen.getByText("We Design Tail-Wagging Websites for Pet Sitters")
    ).toBeInTheDocument();
    expect(
      screen.getByText(
        "Helping pet care businesses create playful, engaging, and effective websites."
      )
    ).toBeInTheDocument();
    expect(screen.getByText("Get a Free Consultation")).toBeInTheDocument();
    expect(screen.getByText("Let's Revamp Your Site")).toBeInTheDocument();
  });

  it("renders the background image", () => {
    render(<HeroSection />);

    const backgroundImage = screen.getByAltText("Pet sitter background");
    expect(backgroundImage).toBeInTheDocument();
    expect(backgroundImage).toHaveAttribute("src", "http://b.io/ext_39-");
  });
});
