/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { render, screen, fireEvent } from "@testing-library/react";
import Navigation from "../components/Navigation";

describe("Navigation", () => {
  it("renders the navigation with correct links", () => {
    render(<Navigation />);

    expect(screen.getByText("Home")).toBeInTheDocument();
    expect(screen.getByText("Services")).toBeInTheDocument();
    expect(screen.getByText("Portfolio")).toBeInTheDocument();
    expect(screen.getByText("Contact")).toBeInTheDocument();
  });

  it("toggles mobile menu when hamburger button is clicked", () => {
    render(<Navigation />);

    const hamburgerButton = screen.getByRole("button", {
      name: /open main menu/i,
    });

    fireEvent.click(hamburgerButton);
    expect(screen.getByText("Home")).toBeVisible();

    fireEvent.click(hamburgerButton);
    expect(screen.queryByText("Home")).not.toBeVisible();
  });
});
